apiVersion: v2
name: youtube-dl-chart
description: A Helm chart for Kubernetes to run youtube-dl jobs for different streamers
type: application
version: 3.2.167
appVersion: 3.2.167
home: https://github.com/liofal/youtube-dl
sources:
  - https://github.com/liofal/youtube-dl
maintainers:
  - name: liofal
    email: lfa@gmx.com
    url: https://github.com/liofal
